### PR TITLE
IE8 has error because of using reserved word

### PR DESCRIPTION
**Pull request by fiskus**

### CODE REVIEW

**Comment by garex** [comment]
And in IE7 too :)

**Comment by garex** [comment]
Marcelo Paez (iugu) said to me:

> Hello, I sent this to Patrick.

If Patrick not overloaded now or he has free time, I think he will merge it soon.

**Comment by pnegri** [comment]
Sorry for the delay guys.

**Comment by pnegri** [comment]
The original intention of this module was to be used in node-js/cassandra :D

**Pull request merged**
